FROM ruby:3.2.0-alpine

# Install requirements to run the app
RUN apk add --no-cache --update \
                                git \
                                build-base \
                                postgresql-dev \
                                tzdata \
                                python3 \
                                curl && \
    curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin && \
    wget https://bootstrap.pypa.io/get-pip.py -O /tmp/get-pip.py && \
    python3 /tmp/get-pip.py && \
    pip install detect-secrets && \
    rm /tmp/get-pip.py

# Set app workdir
WORKDIR /app

EXPOSE 3000

# Set entrypoint
ENTRYPOINT ["./docker-entrypoint.dev.sh"]

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
