FROM ruby:3.2.2-alpine

# Install requirements to run the app
RUN apk add --no-cache --update \
                                git \
                                build-base \
                                postgresql-dev \
                                tzdata \
                                python3 \
                                py3-pip \
                                curl && \
    curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin && \
    pip install git+https://github.com/travis-ci/detect-secrets.git

# Set app workdir
WORKDIR /app

EXPOSE 3000

# Set entrypoint
ENTRYPOINT ["./docker-entrypoint.dev.sh"]

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
