max_threads: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

redis:
  url: <%= ENV.fetch('REDIS_URL', 'redis://redis:6379/1') %>

aws:
  region: <%= ENV.fetch('TRAVIS_LOGS_AWS_REGION', 'us-east-1') %>
  access_key_id: <%= ENV['TRAVIS_LOGS_AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['TRAVIS_LOGS_AWS_SECRET_ACCESS_KEY'] %>
  logs_archive_bucket: <%= ENV.fetch('TRAVIS_LOGS_ARCHIVE_BUCKET', 'archive.travis-ci.com') %>
  logs_archive_raw_bucket: <%= ENV.fetch('TRAVIS_LOGS_ARCHIVE_RAW_BUCKET', 'archive-raw.travis-ci.com') %>

sentry:
  dsn: <%= ENV['SENTRY_DSN'] %>

sidekiq_concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 2) %>

travis_scanner_enabled: <%= ENV.fetch('TRAVIS_SCANNER_ENABLED', false).to_s =~ /^\s*(true|t|yes|y|1)\s*$/i %>

scanner_auth_token: <%= ENV.fetch('TRAVIS_SCANNER_AUTH_TOKEN', 'blablabla') %>

queue_interval: <%= ENV.fetch('TRAVIS_SCANNER_QUEUE_INTERVAL', 30) %> # seconds
requeue_stalled_scans_interval: <%= ENV.fetch('TRAVIS_SCANNER_REQUEUE_STALLED_SCANS_INTERVAL', 40) %> # minutes
queue_limit: <%= ENV.fetch('TRAVIS_SCANNER_QUEUE_LIMIT', 200) %>
queue_batch_size: <%= ENV.fetch('TRAVIS_SCANNER_QUEUE_BATCH_SIZE', 1) %>

plugin_execution_timeout: <%= ENV.fetch('TRAVIS_SCANNER_PLUGIN_EXECUTION_TIMEOUT', 600) %> # seconds

scan_logs_availability_days: <%= ENV.fetch('TRAVIS_SCANNER_SCAN_LOGS_AVAILABILITY_DAYS', 7) %> # days

plugins:
  detect_secrets:
    enabled: <%= ENV.fetch('TRAVIS_SCANNER_DETECT_SECRETS_ENABLED', true).to_s =~ /^\s*(true|t|yes|y|1)\s*$/i %>
    cmdline: <%= ENV.fetch('TRAVIS_SCANNER_DETECT_SECRETS_CMDLINE', 'detect-secrets') %>

  trivy:
    enabled: <%= ENV.fetch('TRAVIS_SCANNER_TRIVY_ENABLED', true).to_s =~ /^\s*(true|t|yes|y|1)\s*$/i %>
    cmdline: <%= ENV.fetch('TRAVIS_SCANNER_TRIVY_CMDLINE', 'trivy') %>
