# Sample configuration file for Sidekiq.
  # Options here can still be overridden by cmd line args.
  # Place this file at config/sidekiq.yml and Sidekiq will
  # pick it up automatically.
---
:pidfile: ./tmp/pids/sidekiq.pid
:concurrency: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
:timeout: 30
:verbose: false
:queues:
  - critical
  - process_logs
  - default
  - scheduled
  - low

:schedule:
  queue_processing_logs_job:
    class: QueueProcessingLogsJob
    queue: scheduled
    cron: '0 */<%= Settings.queue_interval %> * * * *' # Runs when second = 0, every x minutes
