# Sample configuration file for Sidekiq.
  # Options here can still be overridden by cmd line args.
  # Place this file at config/sidekiq.yml and Sidekiq will
  # pick it up automatically.
---
:pidfile: ./tmp/pids/sidekiq.pid
:concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 2) %>
:timeout: 25
:verbose: false
:queues:
  - [critical, 2]
  - default
  - scheduled
  - low
