# Sample configuration file for Sidekiq.
  # Options here can still be overridden by cmd line args.
  # Place this file at config/sidekiq.yml and Sidekiq will
  # pick it up automatically.
---
:pidfile: ./tmp/pids/sidekiq.pid
:concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 2) %>
:timeout: 25
:verbose: false
:queues:
  - [enqueue_processing_logs, 2]
  - [reenqueue_processing_logs, 2]
  - default
  - process_logs
  - manually_enqueued_process_logs

:scheduler:
  schedule:
    enqueue_processing_logs_job:
      class: EnqueueProcessingLogsJob
      queue: enqueue_processing_logs
      cron: '*/<%= ENV.fetch('TRAVIS_SCANNER_QUEUE_INTERVAL', 30) %> * * * * *' # Runs every x seconds

    reenqueue_processing_logs_job:
      class: ReenqueueProcessingLogsJob
      queue: reenqueue_processing_logs
      cron: '0 */1 * * * *' # Runs every 1 minute
