# Sample configuration file for Sidekiq.
  # Options here can still be overridden by cmd line args.
  # Place this file at config/sidekiq.yml and Sidekiq will
  # pick it up automatically.
---
:pidfile: ./tmp/pids/sidekiq.pid
:concurrency: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
:timeout: 30
:verbose: false
:queues:
  - critical
  - process_logs
  - default
  - scheduled
  - enqueue_processing_logs
  - manually_enqueue_processing_logs
  - low

:schedule:
  enqueue_processing_logs_job:
    class: EnqueueProcessingLogsJob
    queue: enqueue_processing_logs
    cron: '0 */<%= ENV.fetch('TRAVIS_SCANNER_QUEUE_INTERVAL', 1) %> * * * *' # Runs when second = 0, every x minutes
